"""empty message

Revision ID: 529dd54fc1d0
Revises: 003d59216867
Create Date: 2023-03-15 13:51:48.606511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '529dd54fc1d0'
down_revision = '003d59216867'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('team', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('sport', sa.String(length=20), nullable=True))
        batch_op.drop_column('year')
        batch_op.drop_column('model')
        batch_op.drop_column('make')
        batch_op.drop_column('color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('make', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('model', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('year', sa.VARCHAR(length=4), autoincrement=False, nullable=True))
        batch_op.drop_column('sport')
        batch_op.drop_column('team')
        batch_op.drop_column('state')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
